begin;
drop policy if exists activities_select_v2 on public.activities;
drop policy if exists activities_insert_v2 on public.activities;
drop policy if exists activities_update_v2 on public.activities;
drop policy if exists activities_delete_v2 on public.activities;
drop policy if exists inscriptions_select_v2 on public.inscriptions;
drop policy if exists inscriptions_update_v2 on public.inscriptions;
drop policy if exists programmes_select_v2 on public.programmes;
drop policy if exists programmes_insert_v2 on public.programmes;
drop policy if exists programmes_update_v2 on public.programmes;
drop policy if exists programmes_delete_v2 on public.programmes;
drop policy if exists profiles_select_superadmin on public.profiles;
drop policy if exists profiles_update_superadmin on public.profiles;
drop trigger if exists trg_audit_activities on public.activities;
drop trigger if exists trg_audit_programmes on public.programmes;
drop trigger if exists trg_audit_profiles on public.profiles;
drop trigger if exists trg_audit_inscriptions on public.inscriptions;
drop function if exists public.audit_v2_change();
drop view if exists public.activity_places;
drop function if exists public.register_inscription_v2(uuid,text,text,text);
drop trigger if exists trg_normalize_registration_fields on public.inscriptions;
drop function if exists public.normalize_registration_fields();
drop trigger if exists trg_activities_touch on public.activities;
drop trigger if exists trg_programmes_touch on public.programmes;
drop trigger if exists trg_profiles_touch on public.profiles;
drop function if exists public.touch_updated_at();
drop function if exists public.can_manage_category(text);
drop function if exists public.is_active_superadmin();
drop table if exists public.audit_logs;
alter table public.activities drop column if exists status,drop column if exists updated_at,drop column if exists date_activite,drop column if exists heure_debut,drop column if exists heure_fin;
alter table public.inscriptions drop column if exists status,drop column if exists updated_at,drop column if exists cancelled_at;
alter table public.profiles drop column if exists active,drop column if exists updated_at,drop column if exists last_login_at;
alter table public.programmes drop column if exists status,drop column if exists heure_debut,drop column if exists heure_fin,drop column if exists activity_id,drop column if exists updated_at;
create or replace view public.activity_places as select a.id activity_id,count(i.id)::integer inscrits from public.activities a left join public.inscriptions i on i.activity_id=a.id group by a.id;
drop policy if exists activities_select_public on public.activities;
drop policy if exists activities_insert_admin on public.activities;
drop policy if exists activities_update_admin on public.activities;
drop policy if exists activities_delete_admin on public.activities;
create policy activities_select_public on public.activities for select using(true);
create policy activities_insert_admin on public.activities for insert with check(exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role='superadmin' or (p.role='ministre' and p.categorie=activities.categorie))));
create policy activities_update_admin on public.activities for update using(exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role='superadmin' or (p.role='ministre' and p.categorie=activities.categorie))));
create policy activities_delete_admin on public.activities for delete using(exists(select 1 from public.profiles p where p.id=auth.uid() and (p.role='superadmin' or (p.role='ministre' and p.categorie=activities.categorie))));
drop policy if exists inscriptions_insert_public on public.inscriptions;
drop policy if exists inscriptions_select_admin on public.inscriptions;
create policy inscriptions_insert_public on public.inscriptions for insert with check(true);
create policy inscriptions_select_admin on public.inscriptions for select using(exists(select 1 from public.profiles p join public.activities a on a.id=inscriptions.activity_id where p.id=auth.uid() and (p.role='superadmin' or (p.role='ministre' and p.categorie=a.categorie))));
drop policy if exists programmes_select_public on public.programmes;
drop policy if exists programmes_insert_admin on public.programmes;
drop policy if exists programmes_update_admin on public.programmes;
drop policy if exists programmes_delete_admin on public.programmes;
create policy programmes_select_public on public.programmes for select using(true);
create policy programmes_insert_admin on public.programmes for insert with check(exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy programmes_update_admin on public.programmes for update using(exists(select 1 from public.profiles p where p.id=auth.uid()));
create policy programmes_delete_admin on public.programmes for delete using(exists(select 1 from public.profiles p where p.id=auth.uid()));
commit;
